version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hussain2012/flask
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    container_name: web
  redis:
    image: redis:4.0.11-alpine
    ports:
      - "6379:6379"
    container_name: redis
